name: Update dist files
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@197ccaa42ab49560ce838a3010eb8345ce086896 # v1
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          file_pattern: dist/**
          add_options: -u --force
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: Pulumi Bot
          commit_user_email: pulumi-bot@users.noreply.github.com
